package com.astgo.fenxiao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PHONE_ADD_INFO".
 */
public class PhoneAddInfo {

    private Long id;
    private String phoneNum;
    /** Not-null value. */
    private String province;
    private String carrier;
    private String city;
    private Integer friend;

    public PhoneAddInfo() {
    }

    public PhoneAddInfo(Long id) {
        this.id = id;
    }

    public PhoneAddInfo(Long id, String phoneNum, String province, String carrier, String city, Integer friend) {
        this.id = id;
        this.phoneNum = phoneNum;
        this.province = province;
        this.carrier = carrier;
        this.city = city;
        this.friend = friend;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /** Not-null value. */
    public String getProvince() {
        return province;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProvince(String province) {
        this.province = province;
    }

    public String getCarrier() {
        return carrier;
    }

    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getFriend() {
        return friend;
    }

    public void setFriend(Integer friend) {
        this.friend = friend;
    }

}
