package com.astgo.naoxuanfeng.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneAddInfoDaoConfig;

    private final PhoneAddInfoDao phoneAddInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneAddInfoDaoConfig = daoConfigMap.get(PhoneAddInfoDao.class).clone();
        phoneAddInfoDaoConfig.initIdentityScope(type);

        phoneAddInfoDao = new PhoneAddInfoDao(phoneAddInfoDaoConfig, this);

        registerDao(PhoneAddInfo.class, phoneAddInfoDao);
    }
    
    public void clear() {
        phoneAddInfoDaoConfig.getIdentityScope().clear();
    }

    public PhoneAddInfoDao getPhoneAddInfoDao() {
        return phoneAddInfoDao;
    }

}
